name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ~0.14.0

      - run: make
